# Generated by Django 5.0.1 on 2024-03-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_alter_site_visitors_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site_visitors',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
