# Generated by Django 5.0.1 on 2024-03-07 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_rename_site_visits_site_visitors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site_visitors',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
