FROM python:3.13-rc-alpine3.19
ENV PYTHONBUFFERED=1

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . /project
WORKDIR /project

COPY ./entrypoint.sh .
ENTRYPOINT [ "sh", "entrypoint.sh" ]