# Generated by Django 5.0.1 on 2024-03-07 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_rename_counter_site_visits'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Site_visits',
            new_name='Site_Visitors',
        ),
    ]
