# Generated by Django 5.0.1 on 2024-03-07 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_alter_counter_count'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Counter',
            new_name='Site_visits',
        ),
    ]
